// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_tts`

Future<void> customInitTts() =>
    RustLib.instance.api.crateApiSimpleCustomInitTts();

Future<void> rSpeak({required String text}) =>
    RustLib.instance.api.crateApiSimpleRSpeak(text: text);

Future<void> rStop() => RustLib.instance.api.crateApiSimpleRStop();

Future<String> speakChineseTest({required String text}) =>
    RustLib.instance.api.crateApiSimpleSpeakChineseTest(text: text);
